//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSiteSaoDima.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Casamento
    {
        public int id { get; set; }
        public string noivo { get; set; }
        public string noiva { get; set; }
        public System.DateTime data { get; set; }
        public string email { get; set; }
        public string solicitante { get; set; }
        public string msg { get; set; }
        public string telefone { get; set; }
        public bool aprovado { get; set; }
    }
}
