//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSiteSaoDima.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evento
    {
        public int id { get; set; }
        public string nome { get; set; }
        public System.DateTime dataHora { get; set; }
        public int tipoEvento { get; set; }
        public byte[] imagemEvento { get; set; }
        public string descricao { get; set; }
        public Nullable<int> usuCriador { get; set; }
    
        public virtual TipoEvento TipoEvento1 { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
